# Generated by Django 4.0 on 2021-12-19 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='users.profile')),
                ('following_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followings', to='users.profile')),
            ],
        ),
    ]
