# Generated by Django 4.0 on 2022-01-02 19:10

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('followed_user', django.db.models.expressions.F('following_user')), _negated=True), name='A follow object with the same following and followed user can not be created'),
        ),
    ]
