# Generated by Django 4.1.dev20211210161305 on 2022-02-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', "0004_follow_can't follow the same user more than once"),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_pictures/default_profile_picture.png', upload_to='profile_pictures/'),
        ),
    ]
