# Generated by Django 4.0 on 2022-01-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_image_alter_post_profile'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='likepost',
            constraint=models.UniqueConstraint(fields=('profile', 'post'), name="Can't like same the post twice"),
        ),
    ]
