# Generated by Django 4.0 on 2022-02-08 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_image'),
        ('core', "0004_likepost_can't like same the post twice"),
    ]

    operations = [
        migrations.CreateModel(
            name='SavePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_posts', to='core.post')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_posts', to='users.profile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='savepost',
            constraint=models.UniqueConstraint(fields=('profile', 'post'), name="You can't save the same post more than once"),
        ),
    ]
