# Generated by Django 4.0 on 2021-12-21 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_email'),
        ('core', '0004_likecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.SmallIntegerField()),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.profile')),
            ],
        ),
    ]
