# Generated by Django 4.0 on 2022-02-12 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_savepost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_created']},
        ),
        migrations.DeleteModel(
            name='LikeComment',
        ),
    ]
